#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#   Optimized for Termux on Android
#
##############################################################################

# Attempt to set APP_HOME
PRG="$0"
while
    APP_HOME=${PRG%"${PRG##*/}"}
    [ -n "$APP_HOME" ] && APP_HOME=$(cd "$APP_HOME" 2>/dev/null && pwd) || break
    PRG=$(readlink "$PRG")
[ -h "$PRG" ]
do
    :
done
APP_HOME=$(cd "${APP_HOME:-./}" 2>/dev/null && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export APP_HOME
export APP_NAME
export APP_BASE_NAME

# Termux-optimized JVM options (reduced memory for mobile)
DEFAULT_JVM_OPTS="-Xmx512m -Xms256m"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/bin/java" ]; then
        JAVACMD=$JAVA_HOME/bin/java
    else
        JAVACMD=$JAVA_HOME/jre/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1; then
        echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
        exit 1
    fi
fi

# Get the Gradle wrapper properties
if [ -z "$GRADLE_WRAPPER_PROPERTIES" ]; then
    GRADLE_WRAPPER_PROPERTIES=$APP_HOME/gradle/wrapper/gradle-wrapper.properties
fi
export GRADLE_WRAPPER_PROPERTIES

# Execute Gradle
exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
