#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as bash or
#       ksh, you may want to invoke the shell explicitly.
#
#   (2) The slightest modification of this script breaks it all. Just don't touch it.
#
#   (3) If you "source" this script you can use the functions defined in it.
#
#   (4) When executed with then no arguments, it builds the project.
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
# Need this for daisy-chained symlinks.
while
    APP_HOME=${PRG%"${PRG##*/}"}
    [ -n "$APP_HOME" ] && APP_HOME=$(cd "$APP_HOME" 2>/dev/null && pwd) || break
    PRG=$(readlink "$PRG")
[ -h "$PRG" ]
do
    :
done
APP_HOME=$(cd "${APP_HOME:-./}" 2>/dev/null && pwd -P) || exit

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export APP_HOME
export APP_NAME
export APP_BASE_NAME

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn() {
    if [ "$QUIET" != yes ]; then
        printf '%s\n' "$*" >&2
    fi
} >&2

die() {
    printf '%s\n' "$1" >&2
    exit "$2"
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
pw=false
darwin=false
case "$(uname)" in
CYGWIN*) cygwin=true ;;
Darwin*) darwin=true ;;
MSYS* | MINGW*) msys=true ;;
*) ;;
esac

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation." 22
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation." 22
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$msys"; then
    case $VERBOSE in
    yes) printf '%s\n' "Increasing the file descriptor limit to maximum." ;;
    esac
    if ! ulimit -n "$MAX_FD"; then
        warn "Could not query maximum file descriptor limit"
    fi
    case $MAX_FD in
    /[0-9]*)
        MAX_FD_LIMIT=$MAX_FD
        ;;
    *)
        warn "Could not parse whitespace as file descriptor limit for $MAX_FD"
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys"; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")
    JAVACMD=$(cygpath --mixed "$JAVACMD")
    for arg in "$@"; do
        if [[ "$arg" =~ ^-?\..*$ ]] || [[ "$arg" =~ ^-?\/.*$ ]]; then
            arg=$(cygpath --path --mixed "$arg")
        fi
        set -- "$@" "$arg"
    done
fi

# Escape application args
save() {
    for i; do printf '%s\n' "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"; done
    printf '%s\n' " "
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell commands we need to protect from word splitting, so let's put them in
#     an array to make the word splitting explicit.
#       -- instead of this...
#           set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS
#       ...we prepend a blank element ($arg) to shift all the others over, so
#       we can drop the next element from "$@" without losing options.
#
#   set -- "$arg" "$@"
#
#   shift # drop next element (previous $1)
#
#   shift # drop next element (previous $1)
#   set -- "$arg" "$@"
#   shift
#   shift
#
# but we cannot rely on them remaining in the "original $@" that was passed,
# so we must use only $arg to perform the actual "work" that this script does
# -- which is simply to find and source.  That is why the way this is written
# below accounts for that possibility.
#   1) the number of existing args
#   2) the number of values after --wrapper-args, so we can determine how many
#      args to shift past for all optional args
#   3) since we cannot reliably count the amount of optional args, we simply
#      process all args

set -- "$CLASSPATH" "$@"

# We use the value of the GRADLE_WRAPPER_PROPERTIES environment variable if
# the user has set that variable.  If the user has not set the variable, we
# use the default value.
#
# When using the Gradle wrapper, this is passed to the Java launcher as:
# -Dorg.gradle.wrapper.properties=<GRADLE_WRAPPER_PROPERTIES>
if [ -z "$GRADLE_WRAPPER_PROPERTIES" ]; then
    GRADLE_WRAPPER_PROPERTIES=$APP_HOME/gradle/wrapper/gradle-wrapper.properties
fi
export GRADLE_WRAPPER_PROPERTIES

# Determine the Java command to use to start the JVM.
find_java_version() {
    if [ -n "$JAVA_HOME" ]; then
        if [ -x "$JAVA_HOME/jre/sh/java" ]; then
            # IBM's JDK on AIX uses strange locations for the executables
            JAVACMD=$JAVA_HOME/jre/sh/java
        else
            JAVACMD=$JAVA_HOME/bin/java
        fi
    else
        JAVACMD=java
    fi
}

# Wrapper startup logic
exec "$JAVACMD" \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"
